"""
Graphify knowledge graph tool — explore the codebase's dependency graph.
Works on the graphify-out/graph.json generated by `graphify extract`.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path

from .base import ToolBase, ToolOutput
from .registry import register_tool

PROJECT_ROOT = Path(__file__).parent.parent
DEFAULT_GRAPH = PROJECT_ROOT / "graphify-out" / "graph.json"


async def _run_graphify(*args) -> tuple[str, int]:
    """Run graphify CLI and return (stdout, exit_code)."""
    try:
        proc = await asyncio.create_subprocess_exec(
            "graphify",
            *args,
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=60.0)
        out = stdout.decode("utf-8", errors="replace")
        err = stderr.decode("utf-8", errors="replace")
        if err:
            out = out + ("\n" + err if out else err)
        return out.strip() or "(no output)", proc.returncode or 0
    except asyncio.TimeoutError:
        return "graphify timed out", -1
    except FileNotFoundError:
        return "ERROR: graphify is not installed. Run: pip install graphifyy", 1
    except Exception as e:
        return f"Error: {e}", 1


class GraphifyTool(ToolBase):
    name = "Graphify"
    description = (
        "Explore the codebase knowledge graph. Subcommands: "
        "god-nodes (architectural hubs), "
        "path A B (shortest dependency path), "
        "explain X (explain a node), "
        "query Q (BFS/DFS traversal), "
        "affected X (reverse impact analysis), "
        "tree (collapsible HTML hierarchy), "
        "info (graph stats)."
    )
    aliases = ["Graph", "DepGraph", "CodeGraph"]
    parameters = {
        "subcommand": {
            "type": "string",
            "description": "Subcommand: god-nodes, path, explain, query, affected, tree, or info",
            "enum": ["god-nodes", "path", "explain", "query", "affected", "tree", "info"],
        },
        "arg1": {
            "type": "string",
            "description": "First argument: source node for path, node name for explain/affected, question for query, or top-N for god-nodes",
        },
        "arg2": {
            "type": "string",
            "description": "Second argument: target node for path, or --dfs for query",
        },
        "depth": {
            "type": "integer",
            "description": "Depth limit for affected traversal (default 2)",
        },
        "top_n": {
            "type": "integer",
            "description": "Number of god-nodes to show (default 10)",
        },
    }

    async def execute(
        self,
        subcommand: str,
        arg1: str = "",
        arg2: str = "",
        depth: int = 2,
        top_n: int = 10,
    ) -> ToolOutput:
        graph_path = DEFAULT_GRAPH

        if subcommand == "info":
            if not graph_path.exists():
                return ToolOutput(
                    text="No graph found. Run: graphify extract <path> --code-only",
                    title="Graphify Info",
                    error=True,
                )
            try:
                data = json.loads(graph_path.read_text(encoding="utf-8"))
                node_list = data.get("nodes", [])
                nodes = len(node_list)
                edges = len(data.get("links", []))
                communities = len(
                    set(n.get("community", -1) for n in node_list if n.get("community", -1) >= 0)
                )
                return ToolOutput(
                    text=f"Graph: {nodes} nodes, {edges} edges, {communities} communities\n"
                    f"Location: {graph_path}",
                    title="Graphify Info",
                    metadata={"nodes": nodes, "edges": edges, "communities": communities},
                )
            except Exception as e:
                return ToolOutput(
                    text=f"Error reading graph: {e}", title="Graphify Info", error=True
                )

        if subcommand == "god-nodes":
            top = arg1 if arg1 and arg1.isdigit() else str(top_n)
            out, code = await _run_graphify("god-nodes", "--graph", str(graph_path), "--top", top)
            return ToolOutput(
                text=out,
                title=f"God Nodes (top {top})",
                error=code != 0,
            )

        if subcommand == "path":
            if not arg1 or not arg2:
                return ToolOutput(text="Usage: path <node_a> <node_b>", error=True)
            out, code = await _run_graphify("path", arg1, arg2, "--graph", str(graph_path))
            return ToolOutput(
                text=out,
                title=f"Path: {arg1} → {arg2}",
                error=code != 0,
            )

        if subcommand == "explain":
            if not arg1:
                return ToolOutput(text="Usage: explain <node_name>", error=True)
            out, code = await _run_graphify("explain", arg1, "--graph", str(graph_path))
            return ToolOutput(
                text=out,
                title=f"Explain: {arg1}",
                error=code != 0,
            )

        if subcommand == "query":
            if not arg1:
                return ToolOutput(text="Usage: query <question>", error=True)
            args = ["query", arg1, "--graph", str(graph_path)]
            if arg2 == "--dfs":
                args.append("--dfs")
            out, code = await _run_graphify(*args)
            return ToolOutput(
                text=out,
                title=f"Query: {arg1[:60]}...",
                error=code != 0,
            )

        if subcommand == "affected":
            if not arg1:
                return ToolOutput(text="Usage: affected <node_name>", error=True)
            out, code = await _run_graphify(
                "affected", arg1, "--depth", str(depth), "--graph", str(graph_path)
            )
            return ToolOutput(
                text=out,
                title=f"Affected by: {arg1}",
                error=code != 0,
            )

        if subcommand == "tree":
            out, code = await _run_graphify("tree", "--graph", str(graph_path))
            tree_path = PROJECT_ROOT / "graphify-out" / "GRAPH_TREE.html"
            if tree_path.exists():
                out += f"\n\nOpen in browser: {tree_path}"
            return ToolOutput(
                text=out,
                title="Graph Tree",
                error=code != 0,
            )

        return ToolOutput(text=f"Unknown subcommand: {subcommand}", error=True)


register_tool(GraphifyTool())
